openapi: 3.0.0
info:
  title: ContactsAPI
  description: A simple RESTful API for managing contact information.
  version: "1.0.0"
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /contacts:
    post:
      summary: Create a new contact
      operationId: createContact
      tags:
        - Contacts
      requestBody:
        description: JSON object representing the new contact
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
            examples:
              default:
                value:
                  name: John Doe
                  email: johndoe@example.com
                  phone: "555-1234"
      responses:
        "201":
          description: Contact created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
  /contacts/{id}:
    get:
      summary: Retrieve a contact by ID
      operationId: getContact
      tags:
        - Contacts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Contact retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        "404":
          description: Contact not found
    put:
      summary: Update an existing contact
      operationId: updateContact
      tags:
        - Contacts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
            examples:
              default:
                value:
                  name: Jane Doe
                  email: janedoe@example.com
                  phone: "555-4321"
      responses:
        "200":
          description: Contact updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
    delete:
      summary: Delete a contact
      operationId: deleteContact
      tags:
        - Contacts
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Contact deleted successfully
components:
  schemas:
    Contact:
      type: object
      required:
        - name
        - email
        - phone
      properties:
        id:
          type: string
          description: The unique identifier for a contact
        name:
          type: string
          description: The name of the contact
        email:
          type: string
          description: The email address of the contact
        phone:
          type: string
          description: The phone number of the contact
